{"value": "Café"},
{"value": "Afghan"},
{"value": "Afghani"},
{"value": "African"},
{"value": "American"},
{"value": "Argentinean"},
{"value": "Armenian"},
{"value": "Asian"},
{"value": "Asian Fusion"},
{"value": "Australian"},
{"value": "Austrian"},
{"value": "Bagels"},
{"value": "Bahamian"},
{"value": "Bakery"},
{"value": "Balti"},
{"value": "Bangladeshi"},
{"value": "Bar"},
{"value": "Barbeque"},
{"value": "Basque"},
{"value": "Belgian"},
{"value": "Bistro"},
{"value": "Brasserie"},
{"value": "Brazilian"},
{"value": "Brew Pub"},
{"value": "British"},
{"value": "Burmese"},
{"value": "Cajun & Creole"},
{"value": "Californian"},
{"value": "Cambodian"},
{"value": "Canadian"},
{"value": "Caribbean"},
{"value": "Central American"},
{"value": "Central European"},
{"value": "Chicken Wings"},
{"value": "Chilean"},
{"value": "Chinese"},
{"value": "Chowder"},
{"value": "Coffee Shop"},
{"value": "Colombian"},
{"value": "Contemporary"},
{"value": "Continental"},
{"value": "Costa Rican"},
{"value": "Creperie"},
{"value": "Croatian"},
{"value": "Cuban"},
{"value": "Czech"},
{"value": "Danish"},
{"value": "Delicatessen"},
{"value": "Dessert"},
{"value": "Dim Sum"},
{"value": "Diner"},
{"value": "Donuts"},
{"value": "Dutch"},
{"value": "Eastern European"},
{"value": "Eclectic"},
{"value": "Ecuadorean"},
{"value": "Egyptian"},
{"value": "English"},
{"value": "Ethiopian"},
{"value": "European"},
{"value": "Family Fare"},
{"value": "Fast Food"},
{"value": "Filipino"},
{"value": "Fish & Chips"},
{"value": "Fondue"},
{"value": "French"},
{"value": "Fusion"},
{"value": "Gastropub"},
{"value": "German"},
{"value": "Greek"},
{"value": "Grill"},
{"value": "Guatemalan"},
{"value": "Halal"},
{"value": "Hamburgers"},
{"value": "Hawaiian"},
{"value": "Healthy"},
{"value": "Hot Dogs"},
{"value": "Hunan"},
{"value": "Hungarian"},
{"value": "Ice Cream"},
{"value": "Indian"},
{"value": "Indonesian"},
{"value": "International"},
{"value": "Irish"},
{"value": "Israeli"},
{"value": "Italian"},
{"value": "Jamaican"},
{"value": "Japanese"},
{"value": "Korean"},
{"value": "Kosher"},
{"value": "Latin"},
{"value": "Latvian"},
{"value": "Lebanese"},
{"value": "Malaysian"},
{"value": "Mediterranean"},
{"value": "Mexican"},
{"value": "Middle Eastern"},
{"value": "Mongolian"},
{"value": "Moroccan"},
{"value": "Native American"},
{"value": "Nepali"},
{"value": "New Zealand"},
{"value": "Nonya"},
{"value": "Noodle"},
{"value": "Noodle Shop"},
{"value": "Norwegian"},
{"value": "Organic"},
{"value": "Oyster Bar"},
{"value": "Pacific Rim"},
{"value": "Pakistani"},
{"value": "Pan-Asian"},
{"value": "Pasta"},
{"value": "Peruvian"},
{"value": "Philippine"},
{"value": "Pizza"},
{"value": "Pizza & Pasta"},
{"value": "Polish"},
{"value": "Polynesian"},
{"value": "Portuguese"},
{"value": "Pub"},
{"value": "Puerto Rican"},
{"value": "Romanian"},
{"value": "Russian"},
{"value": "Salvadoran"},
{"value": "Sandwiches"},
{"value": "Scandinavian"},
{"value": "Scottish"},
{"value": "Seafood"},
{"value": "Singaporean"},
{"value": "Slovenian"},
{"value": "Soups"},
{"value": "South American"},
{"value": "Southwestern"},
{"value": "Spanish"},
{"value": "Sri Lankan"},
{"value": "Steakhouse"},
{"value": "Street Food"},
{"value": "Sushi"},
{"value": "Swedish"},
{"value": "Swiss"},
{"value": "Szechuan"},
{"value": "Taiwanese"},
{"value": "Tapas"},
{"value": "Tea Room"},
{"value": "Thai"},
{"value": "Tibetan"},
{"value": "Tunisian"},
{"value": "Turkish"},
{"value": "Ukrainian"},
{"value": "Vegan"},
{"value": "Vegetarian"},
{"value": "Venezuelan"},
{"value": "Vietnamese"},
{"value": "Welsh"},
{"value": "Wine Bar"},
{"value": "Winery"},
{"value": "Yugoslavian"},